authorName: PujinCheng
experimentName: test_drive
trialConcurrency: 4
maxExecDuration: 4h
maxTrialNum: 1000
trainingServicePlatform: local
searchSpacePath: configs/drive.json
useAnnotation: false
multiThread: true
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
  gpuIndices: 0,1,2,3
trial:
  command: python main.py --config configs/kaggle/test.json
  codeDir: .
  gpuNum: 1
